Repository ase10git/Devfolio, pull requests merged in 2025-08, with the labels that each got.

#11 feat/users-entity
  pom.xml
  src/main/java/io/github/sunday/devfolio/entity/table/user/AuthProvider.java
  src/main/java/io/github/sunday/devfolio/entity/table/user/EmailVerification.java
  src/main/java/io/github/sunday/devfolio/entity/table/user/User.java
Labels: feature

#14 feat(portfolio): 포트폴리오 Entity 추가, 페이지 HTML 파일 추가
  src/main/java/io/github/sunday/devfolio/entity/table/TestModel.java
  src/main/java/io/github/sunday/devfolio/entity/table/portfolio/Portfolio.java
  src/main/java/io/github/sunday/devfolio/entity/table/portfolio/PortfolioCategory.java
  src/main/java/io/github/sunday/devfolio/entity/table/portfolio/PortfolioCategoryMap.java
  src/main/java/io/github/sunday/devfolio/entity/table/portfolio/PortfolioComment.java
  src/main/java/io/github/sunday/devfolio/entity/table/portfolio/PortfolioImage.java
  src/main/java/io/github/sunday/devfolio/entity/table/portfolio/PortfolioLike.java
  src/main/java/io/github/sunday/devfolio/entity/view/TestView.java
  src/main/resources/application-develop.yml
  src/main/resources/static/assets/icon/chat.svg
  src/main/resources/static/assets/icon/chevron-left.svg
  src/main/resources/static/assets/icon/chevron-right.svg
  src/main/resources/static/assets/icon/eye-slash.svg
  src/main/resources/static/assets/icon/eye.svg
  src/main/resources/static/assets/icon/hand-thumbs-up.svg
  src/main/resources/static/assets/icon/search.svg
  src/main/resources/static/assets/icon/x-lg.svg
  src/main/resources/static/css/common/styles.css
  src/main/resources/static/js/portfolio/portfolio-carousel.js
  src/main/resources/static/js/portfolio/portfolio.js
  src/main/resources/static/js/test.js
  src/main/resources/templates/fragments/portfolio_fragments.html
  src/main/resources/templates/portfolio/portfolio.html
  src/main/resources/templates/portfolio/portfolio_detail.html
  src/main/resources/templates/portfolio/portfolio_edit.html
  src/main/resources/templates/portfolio/portfolio_write.html
Labels: feature

#17 [FEAT] 프로필 페이지 MODEL 작업 #16
  pom.xml
  src/main/java/io/github/sunday/devfolio/DTO/ProfileDto.java
  src/main/java/io/github/sunday/devfolio/entity/table/profile/Education.java
  src/main/java/io/github/sunday/devfolio/entity/table/profile/Experience.java
  src/main/java/io/github/sunday/devfolio/entity/table/profile/Follow.java
  src/main/java/io/github/sunday/devfolio/entity/table/profile/Resume.java
  src/main/java/io/github/sunday/devfolio/entity/table/profile/ResumeFile.java
  src/main/java/io/github/sunday/devfolio/entity/table/profile/Skill.java
  src/main/java/io/github/sunday/devfolio/entity/table/profile/Training.java
  src/main/java/io/github/sunday/devfolio/repository/FollowRepository.java
  src/main/java/io/github/sunday/devfolio/repository/ResumeRepository.java
  src/main/java/io/github/sunday/devfolio/repository/UserRepository.java
  src/main/java/io/github/sunday/devfolio/service/ProfileService.java
Labels: feature

#18 feat(portfolio) : 포트폴리오 페이지 CSS 추가 및 HTML 수정
  src/main/java/io/github/sunday/devfolio/controller/PortfolioController.java
  src/main/java/io/github/sunday/devfolio/controller/TestController.java
  src/main/java/io/github/sunday/devfolio/dto/TestDto.java
  src/main/java/io/github/sunday/devfolio/entity/table/community/CommunityComment.java
  src/main/java/io/github/sunday/devfolio/entity/table/community/CommunityLike.java
  src/main/java/io/github/sunday/devfolio/entity/table/community/CommunityPost.java
  src/main/java/io/github/sunday/devfolio/entity/table/portfolio/Portfolio.java
  src/main/java/io/github/sunday/devfolio/entity/table/portfolio/PortfolioCategory.java
  src/main/java/io/github/sunday/devfolio/entity/table/portfolio/PortfolioCategoryMap.java
  src/main/java/io/github/sunday/devfolio/entity/table/portfolio/PortfolioComment.java
  src/main/java/io/github/sunday/devfolio/entity/table/portfolio/PortfolioImage.java
  src/main/java/io/github/sunday/devfolio/entity/table/portfolio/PortfolioLike.java
  src/main/java/io/github/sunday/devfolio/entity/table/profile/Follow.java
  src/main/java/io/github/sunday/devfolio/entity/table/profile/Resume.java
  src/main/java/io/github/sunday/devfolio/repository/FollowRepository.java
  src/main/java/io/github/sunday/devfolio/repository/ResumeRepository.java
  src/main/java/io/github/sunday/devfolio/repository/TestRepository.java
  src/main/java/io/github/sunday/devfolio/repository/UserRepository.java
  src/main/java/io/github/sunday/devfolio/service/ProfileService.java
  src/main/java/io/github/sunday/devfolio/service/TestService.java
  src/main/resources/static/assets/icon/heart-fill.svg
  src/main/resources/static/assets/icon/heart.svg
  src/main/resources/static/assets/icon/image.svg
  src/main/resources/static/assets/icon/pencil.svg
  src/main/resources/static/assets/icon/person-fill.svg
  src/main/resources/static/assets/testimg
  src/main/resources/static/css/common/portfolio_card.css
  src/main/resources/static/css/common/styles.css
  src/main/resources/static/css/portfolio/portfolio.css
  src/main/resources/static/css/portfolio/portfolio_detail.css
  src/main/resources/static/css/portfolio/portfolio_write.css
  src/main/resources/templates/fragments/portfolio_fragments.html
  src/main/resources/templates/portfolio/portfolio.html
  src/main/resources/templates/portfolio/portfolio_detail.html
  src/main/resources/templates/portfolio/portfolio_edit.html
  src/main/resources/templates/portfolio/portfolio_write.html
Labels: feature

#36 feat: 로컬 로그인, OAuth2 로그인 기능 (#30) TODO: 로컬 회원가입과 OAuth2 로그인 시 중복되는 부분 처리, OAuth2 로그인 시 아이디, 비밀번호 등 자동생성 등
  pom.xml
  src/main/java/io/github/sunday/devfolio/config/AppConfig.java
  src/main/java/io/github/sunday/devfolio/config/SecurityConfig.java
  src/main/java/io/github/sunday/devfolio/config/WebConfig.java
  src/main/java/io/github/sunday/devfolio/controller/MainController.java
  src/main/java/io/github/sunday/devfolio/controller/OAuth2Controller.java
  src/main/java/io/github/sunday/devfolio/controller/UserController.java
  src/main/java/io/github/sunday/devfolio/entity/table/user/User.java
  src/main/java/io/github/sunday/devfolio/interceptor/LoginUserInterceptor.java
  src/main/java/io/github/sunday/devfolio/repository/UserRepository.java
  src/main/java/io/github/sunday/devfolio/repository/portfolio/PortfolioQueryDslRepository.java
  src/main/java/io/github/sunday/devfolio/service/CustomUserDetailsService.java
  src/main/java/io/github/sunday/devfolio/service/UserService.java
  src/main/java/io/github/sunday/devfolio/service/impl/UserServiceImpl.java
  src/main/java/io/github/sunday/devfolio/util/TestUtil.java
  src/main/resources/static/assets/icon/google-logo.svg
  src/main/resources/templates/login.html
  src/main/resources/templates/main.html
  src/main/resources/templates/signup.html
Labels: feature

#39 feat(portfolio): 포트폴리오 상세보기 기능 추가
  pom.xml
  src/main/java/io/github/sunday/devfolio/DTO/common/MultipartImage.java
  src/main/java/io/github/sunday/devfolio/DTO/portfolio/PortfolioDetailDto.java
  src/main/java/io/github/sunday/devfolio/DTO/portfolio/PortfolioImageDto.java
  src/main/java/io/github/sunday/devfolio/DTO/portfolio/PortfolioListDto.java
  src/main/java/io/github/sunday/devfolio/config/SecurityConfig.java
  src/main/java/io/github/sunday/devfolio/controller/common/EditorImageController.java
  src/main/java/io/github/sunday/devfolio/controller/portfolio/PortfolioController.java
  src/main/java/io/github/sunday/devfolio/exception/common/IncorrectImageTargetException.java
  src/main/java/io/github/sunday/devfolio/exception/portfolio/NoWriterFoundException.java
  src/main/java/io/github/sunday/devfolio/exception/portfolio/PortfolioNotFoundException.java
  src/main/java/io/github/sunday/devfolio/service/portfolio/PortfolioImageService.java
  src/main/java/io/github/sunday/devfolio/service/portfolio/PortfolioService.java
  src/main/resources/application-develop.yml
  src/main/resources/static/css/common/portfolio_card.css
  src/main/resources/static/css/portfolio/portfolio.css
  src/main/resources/static/css/portfolio/portfolio_detail.css
  src/main/resources/static/js/ckeditor5/ckeditor5-config.js
  src/main/resources/static/js/portfolio/portfolio-write-ckeditor5.js
  src/main/resources/static/js/portfolio/portfolio-write.js
  src/main/resources/templates/error.html
  src/main/resources/templates/fragments/portfolio_fragments.html
  src/main/resources/templates/portfolio/portfolio.html
  src/main/resources/templates/portfolio/portfolio_detail.html
  src/main/resources/templates/portfolio/portfolio_edit.html
  src/main/resources/templates/portfolio/portfolio_write.html
Labels: feature

#43 fix: 소셜 로그인 오류 해결 1. 소셜 로그인으로 회원가입 한 사용자가 다시 로그인 하는 경우 오류 발생 -> 이메일로 기존 사용자 조회 후 로컬 회원이면 소셜로그인 차단, 기존 소셜 회원이면 로그인 처리 2. login 페이지에서 오류 메세지 소셜 로그인과 로컬 로그인을 분리
  pom.xml
  src/main/java/io/github/sunday/devfolio/controller/OAuth2Controller.java
  src/main/java/io/github/sunday/devfolio/interceptor/LoginUserInterceptor.java
  src/main/resources/templates/login.html
Labels: feature

#37 feat(profile): 프로필 조회, 수정, 팔로우 기능
  src/main/java/io/github/sunday/devfolio/DTO/ProfileDto.java
  src/main/java/io/github/sunday/devfolio/controller/ProfileController.java
  src/main/java/io/github/sunday/devfolio/controller/ProfileViewController.java
  src/main/java/io/github/sunday/devfolio/dto/ProfileDto.java
  src/main/java/io/github/sunday/devfolio/dto/ProfileUpdateRequest.java
  src/main/java/io/github/sunday/devfolio/service/ProfileService.java
  src/main/java/io/github/sunday/devfolio/service/ProfileUpdateService.java
  src/main/resources/static/css/profilepage/profile.css
  src/main/resources/templates/profile/profile.html
  src/main/resources/templates/profile/profile_edit.html
Labels: feature

#47 feat(portfolio): 포트폴리오 제거, 좋아요 기능 추가
  src/main/java/io/github/sunday/devfolio/DTO/portfolio/PortfolioEditRequestDto.java
  src/main/java/io/github/sunday/devfolio/DTO/portfolio/PortfolioWriteRequestDto.java
  src/main/java/io/github/sunday/devfolio/annotation/common/DateValid.java
  src/main/java/io/github/sunday/devfolio/controller/ProfileViewController.java
  src/main/java/io/github/sunday/devfolio/controller/portfolio/PortfolioController.java
  src/main/java/io/github/sunday/devfolio/controller/portfolio/PortfolioRestController.java
  src/main/java/io/github/sunday/devfolio/repository/portfolio/PortfolioLikeRepository.java
  src/main/java/io/github/sunday/devfolio/service/ProfileService.java
  src/main/java/io/github/sunday/devfolio/service/portfolio/PortfolioCommentService.java
  src/main/java/io/github/sunday/devfolio/service/portfolio/PortfolioImageService.java
  src/main/java/io/github/sunday/devfolio/service/portfolio/PortfolioLikeService.java
  src/main/java/io/github/sunday/devfolio/service/portfolio/PortfolioService.java
  src/main/java/io/github/sunday/devfolio/validator/common/DateValidator.java
  src/main/resources/static/css/portfolio/portfolio_detail.css
  src/main/resources/static/js/portfolio/portfolio-detail.js
  src/main/resources/templates/fragments/portfolio_fragments.html
  src/main/resources/templates/portfolio/portfolio.html
  src/main/resources/templates/portfolio/portfolio_detail.html
Labels: feature

#50 feat(portfolio): Alan AI에 템플릿 요청 기능 추가
  pom.xml
  src/main/java/io/github/sunday/devfolio/DTO/common/AlanResponseDto.java
  src/main/java/io/github/sunday/devfolio/DTO/portfolio/PortfolioTemplateDto.java
  src/main/java/io/github/sunday/devfolio/DTO/portfolio/PortfolioTemplateRequestDto.java
  src/main/java/io/github/sunday/devfolio/config/RestClientConfig.java
  src/main/java/io/github/sunday/devfolio/config/SecurityConfig.java
  src/main/java/io/github/sunday/devfolio/config/WebConfig.java
  src/main/java/io/github/sunday/devfolio/controller/common/AIController.java
  src/main/java/io/github/sunday/devfolio/service/common/AIService.java
  src/main/java/io/github/sunday/devfolio/service/portfolio/PortfolioCategoryService.java
  src/main/java/io/github/sunday/devfolio/service/portfolio/PortfolioLikeService.java
  src/main/java/io/github/sunday/devfolio/service/portfolio/PortfolioService.java
  src/main/java/io/github/sunday/devfolio/utils/StringExtractUtils.java
  src/main/java/io/github/sunday/devfolio/validator/portfolio/PortfolioCategoryValidator.java
  src/main/resources/application-develop.yml
  src/main/resources/application-production.yml
  src/main/resources/static/css/common/styles.css
  src/main/resources/static/css/portfolio/portfolio.css
  src/main/resources/static/css/portfolio/portfolio_detail.css
  src/main/resources/static/css/portfolio/portfolio_write.css
  src/main/resources/static/js/portfolio/portfolio-write-ckeditor5.js
  src/main/resources/static/js/portfolio/portfolio-write.js
  src/main/resources/static/prompts/portfolio_template.txt
  src/main/resources/templates/portfolio/portfolio_edit.html
  src/main/resources/templates/portfolio/portfolio_write.html
Labels: feature

#54 feat(community): 커뮤니티 검색 서버 동작 1차 추가
  src/main/java/io/github/sunday/devfolio/DTO/community/CommunitySearchRequestDto.java
  src/main/java/io/github/sunday/devfolio/annotation/community/CommunityCategoryValid.java
  src/main/java/io/github/sunday/devfolio/controller/community/CommunityController.java
  src/main/java/io/github/sunday/devfolio/entity/table/community/Category.java
  src/main/java/io/github/sunday/devfolio/entity/table/community/CommunityPost.java
  src/main/java/io/github/sunday/devfolio/enums/CommunitySort.java
  src/main/java/io/github/sunday/devfolio/repository/community/CommunityQueryDslRepository.java
  src/main/java/io/github/sunday/devfolio/service/community/CommunityService.java
  src/main/java/io/github/sunday/devfolio/validator/community/CommunityCategoryValidator.java
  src/main/resources/static/css/common/portfolio_card.css
  src/main/resources/static/css/common/styles.css
  src/main/resources/static/css/portfolio/portfolio.css
  src/main/resources/static/css/portfolio/portfolio_detail.css
  src/main/resources/static/css/portfolio/portfolio_write.css
  src/main/resources/static/js/portfolio/portfolio-detail.js
  src/main/resources/templates/portfolio/portfolio.html
  src/main/resources/templates/portfolio/portfolio_detail.html
  src/main/resources/templates/portfolio/portfolio_edit.html
  src/main/resources/templates/portfolio/portfolio_write.html
Labels: feature

#57 feat: 프로필, 프로필 수정 페이지 연동 및 기능 구현 [#56] 1. 헤더에 프로필 페이지 추가 2. 사용자 본인 프로필 페이지 접속 시 좋아요 목록 보이기 3. 사용자 본인 프로필 페이지 접속 시 팔로우 버튼 프로필 수정 버튼으로 바꾸기 4. 프로필 수정 페이지 연동 5. 프로필 수정 페이지 닉네임 중복 확인 구현 6. 프로필 수정 페이지 이메일 인증 구현
  src/main/java/io/github/sunday/devfolio/controller/ProfileController.java
  src/main/java/io/github/sunday/devfolio/controller/ProfileViewController.java
  src/main/java/io/github/sunday/devfolio/dto/ProfileDto.java
  src/main/java/io/github/sunday/devfolio/entity/table/profile/Follow.java
  src/main/java/io/github/sunday/devfolio/entity/table/profile/Resume.java
  src/main/java/io/github/sunday/devfolio/repository/ResumeRepository.java
  src/main/java/io/github/sunday/devfolio/repository/UserRepository.java
  src/main/java/io/github/sunday/devfolio/repository/community/CommunityLikeRepository.java
  src/main/java/io/github/sunday/devfolio/repository/community/CommunityPostRepository.java
  src/main/java/io/github/sunday/devfolio/repository/portfolio/PortfolioLikeRepository.java
  src/main/java/io/github/sunday/devfolio/repository/portfolio/PortfolioRepository.java
  src/main/java/io/github/sunday/devfolio/service/ProfileService.java
  src/main/java/io/github/sunday/devfolio/service/ProfileUpdateService.java
  src/main/resources/static/css/profilepage/profile.css
  src/main/resources/static/js/profile/profile_edit.js
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/profile/profile.html
  src/main/resources/templates/profile/profile_edit.html
Labels: feature

#58 feat(portfolio) : 사용자 정보 연동
  src/main/java/io/github/sunday/devfolio/controller/community/CommunityController.java
  src/main/java/io/github/sunday/devfolio/controller/portfolio/PortfolioController.java
  src/main/java/io/github/sunday/devfolio/controller/portfolio/PortfolioRestController.java
  src/main/java/io/github/sunday/devfolio/service/portfolio/PortfolioService.java
  src/main/resources/static/js/ckeditor5/ckeditor5-config.js
  src/main/resources/templates/portfolio/portfolio.html
  src/main/resources/templates/portfolio/portfolio_detail.html
  src/main/resources/templates/portfolio/portfolio_edit.html
Labels: feature

#72 style : 메인 페이지 내용 추가 및 디자인 수정
  src/main/resources/static/assets/images/devfolio-logo-title.png
  src/main/resources/static/assets/images/service-community.png
  src/main/resources/static/assets/images/service-portfolio.png
  src/main/resources/static/assets/images/service-profile.png
  src/main/resources/static/css/common/main.css
  src/main/resources/templates/main.html
Labels: feature

#74 style: 프로필 페이지의 프로필 부분 간격 수정
  src/main/resources/templates/profile/profile.html
Labels: feature

#78 refactor : 이미지 유효성 체크에서 이미지 용량 한도 수정
  src/main/java/io/github/sunday/devfolio/service/common/SecureImageService.java
Labels: bug

#80 style : 게시글 작성 및 상세 페이지 UI/UX 개편
  src/main/java/io/github/sunday/devfolio/config/SecurityConfig.java
  src/main/resources/static/assets/icon/search_white.svg
  src/main/resources/static/css/common/styles.css
  src/main/resources/static/css/community/community_detail.css
  src/main/resources/static/css/community/community_list.css
  src/main/resources/static/js/community/community-write.js
  src/main/resources/templates/community/community_detail.html
  src/main/resources/templates/community/community_list.html
  src/main/resources/templates/community/community_write.html
  src/main/resources/templates/fragments/comment_tree.html
Labels: feature

#84 Fix : 답글 작성, 삭제 기능 수정
  src/main/resources/static/js/community/community-comment.js
  src/main/resources/templates/fragments/comment_tree.html
Labels: feature

#86 Fix : 페이지네이션 수정
  src/main/java/io/github/sunday/devfolio/controller/community/CommunityController.java
  src/main/java/io/github/sunday/devfolio/repository/community/CommunityQueryDslRepository.java
  src/main/java/io/github/sunday/devfolio/service/community/CommunityService.java
  src/main/resources/templates/community/community_list.html
Labels: bug

#88 Feat : 카테고리 유효성 검사 추가
  src/main/java/io/github/sunday/devfolio/DTO/community/CommentUpdateRequestDto.java
  src/main/java/io/github/sunday/devfolio/DTO/community/PostCreateRequestDto.java
  src/main/java/io/github/sunday/devfolio/controller/community/CommunityController.java
  src/main/resources/static/js/community/community-write.js
  src/main/resources/templates/community/community_write.html
Labels: feature

#90 Feat : 조회수 동작 수정
  src/main/java/io/github/sunday/devfolio/service/community/CommunityService.java
  src/main/resources/static/js/community/community-list.js
Labels: feature

#91 Refactor/main
  src/main/java/io/github/sunday/devfolio/controller/ProfileViewController.java
  src/main/java/io/github/sunday/devfolio/service/ProfileService.java
  src/main/resources/templates/main.html
  src/main/resources/templates/portfolio/portfolio_detail.html
  src/main/resources/templates/profile/profile.html
Labels: bug

#94 Feat : 기본 프로필 이미지 추가
  src/main/resources/templates/community/community_detail.html
  src/main/resources/templates/community/community_list.html
  src/main/resources/templates/fragments/comment_tree.html
Labels: feature

#95 doc : README.md 업데이트
  README.md
Labels: documentation

#98 refactor : 패키지 구조 변경
  src/main/java/io/github/sunday/devfolio/DTO/auth/UserSignupDto.java
  src/main/java/io/github/sunday/devfolio/DTO/community/CommunitySearchRequestDto.java
  src/main/java/io/github/sunday/devfolio/DTO/portfolio/PortfolioPageRequestDto.java
  src/main/java/io/github/sunday/devfolio/DTO/portfolio/PortfolioSearchRequestDto.java
  src/main/java/io/github/sunday/devfolio/DTO/user/ProfileDto.java
  src/main/java/io/github/sunday/devfolio/DTO/user/ProfileUpdateRequest.java
  src/main/java/io/github/sunday/devfolio/config/CommunityControllerAdvice.java
  src/main/java/io/github/sunday/devfolio/config/CustomUserDetails.java
  src/main/java/io/github/sunday/devfolio/config/PortfolioControllerAdvice.java
  src/main/java/io/github/sunday/devfolio/config/SecurityConfig.java
  src/main/java/io/github/sunday/devfolio/config/WebConfig.java
  src/main/java/io/github/sunday/devfolio/controller/auth/EmailVerificationController.java
  src/main/java/io/github/sunday/devfolio/controller/common/MainController.java
  src/main/java/io/github/sunday/devfolio/controller/community/CommunityController.java
  src/main/java/io/github/sunday/devfolio/controller/portfolio/PortfolioController.java
  src/main/java/io/github/sunday/devfolio/controller/user/ProfileController.java
  src/main/java/io/github/sunday/devfolio/controller/user/ProfileViewController.java
  src/main/java/io/github/sunday/devfolio/controller/user/UserController.java
  src/main/java/io/github/sunday/devfolio/enums/common/ImageTarget.java
  src/main/java/io/github/sunday/devfolio/enums/community/CommunitySort.java
  src/main/java/io/github/sunday/devfolio/enums/portfolio/PortfolioSort.java
  src/main/java/io/github/sunday/devfolio/interceptor/LoginUserInterceptor.java
  src/main/java/io/github/sunday/devfolio/repository/auth/EmailVerificationRepository.java
  src/main/java/io/github/sunday/devfolio/repository/portfolio/PortfolioQueryDslRepository.java
  src/main/java/io/github/sunday/devfolio/repository/user/FollowRepository.java
  src/main/java/io/github/sunday/devfolio/repository/user/ResumeRepository.java
  src/main/java/io/github/sunday/devfolio/repository/user/UserRepository.java
  src/main/java/io/github/sunday/devfolio/scheduler/EmailVerificationCleanupTask.java
  src/main/java/io/github/sunday/devfolio/service/auth/CustomOAuth2UserService.java
  src/main/java/io/github/sunday/devfolio/service/auth/CustomUserDetailsService.java
  src/main/java/io/github/sunday/devfolio/service/auth/EmailService.java
  src/main/java/io/github/sunday/devfolio/service/auth/impl/EmailServiceImpl.java
  src/main/java/io/github/sunday/devfolio/service/common/AIService.java
  src/main/java/io/github/sunday/devfolio/service/common/SecureImageService.java
  src/main/java/io/github/sunday/devfolio/service/community/CommunityService.java
  src/main/java/io/github/sunday/devfolio/service/portfolio/PortfolioLikeService.java
  src/main/java/io/github/sunday/devfolio/service/portfolio/PortfolioService.java
  src/main/java/io/github/sunday/devfolio/service/user/ProfileService.java
  src/main/java/io/github/sunday/devfolio/service/user/ProfileUpdateService.java
  src/main/java/io/github/sunday/devfolio/service/user/UserService.java
  src/main/java/io/github/sunday/devfolio/service/user/impl/UserServiceImpl.java
  src/main/resources/application-develop.yml
  src/main/resources/application-production.yml
Labels: refactor

#100 fix(community) : updatedAt Not null 설정
  src/main/java/io/github/sunday/devfolio/DTO/community/PostCreateRequestDto.java
  src/main/java/io/github/sunday/devfolio/entity/table/community/CommunityPost.java
Labels: bug
